# Generated by Django 4.0.6 on 2022-08-17 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=50)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='verificacion')),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Deposito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='verificacion')),
                ('valor', models.FloatField()),
                ('telefono', models.CharField(max_length=20)),
                ('banco', models.CharField(max_length=20)),
                ('cuenta', models.CharField(max_length=20)),
                ('respuesta', models.BooleanField(blank=True, null=True)),
                ('documento', models.ImageField(blank=True, null=True, upload_to='verificacion')),
                ('mensaje', models.TextField(blank=True, null=True)),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deposito.usuario')),
            ],
        ),
    ]
