# Generated by Django 4.0.6 on 2022-08-17 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deposito', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=50)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='verificacion')),
                ('monto', models.FloatField()),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='deposito',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deposito.persona'),
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
