# Generated by Django 4.0.6 on 2022-08-16 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verificacion', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='verificacion',
            old_name='verificado',
            new_name='respuesta',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='verificacion'),
        ),
        migrations.AlterField(
            model_name='verificacion',
            name='documento',
            field=models.ImageField(blank=True, null=True, upload_to='verificacion'),
        ),
        migrations.AlterField(
            model_name='verificacion',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='verificacion'),
        ),
        migrations.AlterField(
            model_name='verificacion',
            name='pose1',
            field=models.ImageField(blank=True, null=True, upload_to='verificacion'),
        ),
        migrations.AlterField(
            model_name='verificacion',
            name='pose2',
            field=models.ImageField(blank=True, null=True, upload_to='verificacion'),
        ),
        migrations.AlterField(
            model_name='verificacion',
            name='selfie1',
            field=models.ImageField(blank=True, null=True, upload_to='verificacion'),
        ),
        migrations.AlterField(
            model_name='verificacion',
            name='selfie2',
            field=models.ImageField(blank=True, null=True, upload_to='verificacion'),
        ),
    ]
